### ISSUE TITLE
составить юзкейс

### ISSUE THREAD

**Issue by n3wstar** [ytug30/ytug#4]
написать юзкейсы которые содержат следующие данные:
-кто использует сайт или приложение
-что пользователь хочет сделать
-цель пользователя
-шаги, которые делает пользователь, чтобы совершить определенное действие
-описание того, как сайт или приложение реагируют на действия пользователя.

**Comment by dashuulka** [comment]
[usecase.docx](https://github.com/ytug30/ytug/files/11243302/usecase.docx)

**Comment by n3wstar** [comment]
исправленный usecase

[usecase.docx](https://github.com/ytug30/ytug/files/11523122/usecase.docx)
